name: tagpr

on:
  push:
    branches:
      - main

permissions:
  # tagpr が PR を作成する
  pull-requests: write
  contents: write
  # dispatch のため https://docs.github.com/ja/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
  actions: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tagpr
        name: Tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Release Workflow(only when tagged)
        uses: actions/github-script@v6
        if: "steps.tagpr.outputs.tag != ''"
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yaml',
              ref: "refs/tags/${{ steps.tagpr.outputs.tag }}",
            })
